import type { Metadata } from 'next';
import { GraduationCap } from 'lucide-react';
import dealsRaw from '@/content/deals.json';
import { dealSchema, type Deal } from '@/lib/schemas';
import { SITE_URL } from '@/lib/site';
import { CouponCard } from '@/components/discounts/CouponCard';
import { ItemPageSchema } from '@/components/SEO/StructuredData';

/**
 * IMPORTANT, read before editing.
 *
 * `/coupons/`, `/linux-foundation-coupon/**` and `/finops-coupon/**` already
 * exist, already rank, and are generated by ../scripts/build-blog.mjs. This page
 * must NOT become a fourth listing of the same codes, or it competes with them
 * for the same queries and all four lose.
 *
 * So the split is by intent, not by product:
 *   /coupons/   -> price comparison. "Which code is cheapest for me?"
 *   /discounts/ -> study path.       "Which exam should I take, and in what order?"
 *
 * This page therefore leads with the roadmap and treats the code as the footer
 * of each card. It carries no Product/Offer JSON-LD, deliberately: that schema
 * already lives on the per-cert pages and duplicating it splits the rich result.
 * The canonical points here, but every card links back to the cert page which is
 * the page built to win the commercial query.
 */

const TITLE = 'Certification study paths · Rushabh Shah';
const DESCRIPTION =
  'Which cloud native certification to take, in what order, and what each one actually tests. Includes partner discount codes for the Linux Foundation and FinOps Foundation exams.';

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/discounts/` },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${SITE_URL}/discounts/`,
    images: [{ url: `${SITE_URL}/assets/og-lf-coupon.jpg`, width: 1200, height: 630 }],
  },
};

const deals: Deal[] = dealsRaw.map((d) => dealSchema.parse(d));

/** The educational spine. Each stage links to writing that justifies the advice. */
const ROADMAP = [
  {
    stage: 'Start here',
    when: 'You have used Kubernetes but never administered it',
    exams: ['Kubernetes and Cloud Native Associate (KCNA)'],
    guide: { href: '/blog/kcna-worth-it/', label: 'Is the KCNA worth it?' },
  },
  {
    stage: 'The one employers check',
    when: 'A role involves running clusters in production, not just deploying to them',
    exams: ['Certified Kubernetes Administrator (CKA)'],
    guide: { href: '/blog/cka-exam-guide/', label: 'What the CKA actually tests' },
  },
  {
    stage: 'Pick your branch',
    when: 'You have the CKA and want depth rather than breadth',
    exams: [
      'Certified Kubernetes Application Developer (CKAD)',
      'Certified Kubernetes Security Specialist (CKS)',
    ],
    guide: { href: '/blog/cka-vs-ckad-vs-cks/', label: 'CKA vs CKAD vs CKS, and which to take' },
  },
  {
    stage: 'Observability',
    when: 'You own dashboards and alerts, not just workloads',
    exams: ['Prometheus Certified Associate (PCA)', 'OpenTelemetry Certified Associate (OTCA)'],
    guide: { href: '/blog/pca-otca-review/', label: 'PCA and OTCA, reviewed' },
  },
];

export default function DiscountsPage() {
  const guideTitles = new Map(
    ROADMAP.flatMap((r) => [[r.guide.href.split('/')[2] ?? '', r.guide.label] as const]),
  );

  return (
    <main id="main" className="container mx-auto px-6 py-16">
      <ItemPageSchema
        path="/discounts/"
        name={TITLE}
        description={DESCRIPTION}
        breadcrumb={[
          { name: 'Home', path: '/' },
          { name: 'Study paths', path: '/discounts/' },
        ]}
      />

      <header className="mb-14 max-w-3xl">
        <p className="mb-3 font-fira text-xs uppercase tracking-wider text-primary">
          <GraduationCap aria-hidden="true" className="mr-2 inline h-3.5 w-3.5" />
          Study paths
        </p>
        <h1 className="mb-4 text-4xl font-bold leading-tight tracking-tight text-strong md:text-5xl">
          Which certification to take, and in what order
        </h1>
        <p className="text-base leading-relaxed text-body">
          I hold the partner codes below, so I have an obvious interest in you buying an exam. That
          is exactly why the order matters more than the discount. Taking the wrong exam at the
          wrong time is expensive whatever you paid for it. Each stage links to what I have written
          about that exam, including the ones I think most people should skip.
        </p>
        <p className="mt-4 font-fira text-xs text-muted">
          Only comparing prices?{' '}
          <a href="/coupons/" className="text-primary hover:underline">
            The side-by-side code comparison lives here
          </a>
          .
        </p>
      </header>

      <section aria-labelledby="roadmap" className="mb-16">
        <h2 id="roadmap" className="mb-6 text-2xl font-bold text-strong">
          The path
        </h2>
        <ol className="list-none space-y-4 p-0">
          {ROADMAP.map((step, i) => (
            <li
              key={step.stage}
              className="rounded-lg border border-[var(--border-color)] bg-[var(--panel-color)] p-5"
            >
              <div className="flex flex-wrap items-baseline gap-3">
                <span className="font-fira text-sm text-primary">0{i + 1}.</span>
                <h3 className="text-lg font-bold text-strong">{step.stage}</h3>
              </div>
              <p className="mt-2 text-sm text-muted">{step.when}</p>
              <ul className="mt-3 flex flex-wrap gap-2 p-0">
                {step.exams.map((e) => (
                  <li
                    key={e}
                    className="list-none rounded-full bg-primary-tint/10 px-3 py-1 font-fira text-xs text-primary"
                  >
                    {e}
                  </li>
                ))}
              </ul>
              <a
                href={step.guide.href}
                className="mt-4 inline-block font-fira text-xs text-primary hover:underline"
              >
                {step.guide.label} →
              </a>
            </li>
          ))}
        </ol>
      </section>

      <section aria-labelledby="codes">
        <h2 id="codes" className="mb-2 text-2xl font-bold text-strong">
          The codes
        </h2>
        <p className="mb-6 max-w-2xl text-sm text-muted">
          Both are evergreen partner codes with no expiry. During a Linux Foundation flash sale a
          sitewide discount can beat RUSHABH30, and when that happens the{' '}
          <a href="/linux-foundation-coupon/" className="text-primary hover:underline">
            coupon hub
          </a>{' '}
          says so on the page rather than letting you overpay.
        </p>
        <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
          {deals.map((deal) => (
            <CouponCard
              key={`${deal.promoCode}-${deal.examName}`}
              deal={deal}
              studyGuideTitle={
                deal.studyGuideSlug ? guideTitles.get(deal.studyGuideSlug) : undefined
              }
            />
          ))}
        </div>
      </section>
    </main>
  );
}
